# Generated by Django 4.1.7 on 2023-11-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
