# Generated by Django 4.1.7 on 2023-11-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note_app", "0004_alter_note_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
            ],
        ),
    ]
